### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by AliceAponasko** [marty-suzuki/SABlurImageView#32]
Hi!
`feature/swift3` branch throws 4 errors in XCode 8.0. 

![screen shot 2016-09-14 at 5 55 10 pm](https://cloud.githubusercontent.com/assets/7119339/18533981/6601c3d2-7aa4-11e6-8447-bca2cf4a2350.png)

**Comment by 8masterofpuppets8** [comment]
Yep I am seeing the same errors. Any chance they might be fixed up soon? Thanks!

**Comment by marty-suzuki** [comment]
Hi, @AliceAponasko and @8masterofpuppets8!

Thank you for your reporting.
I've released 3.0.0!
It is fixed those errors.
Please check it!

Thank you.
