### ISSUE TITLE
IOS 10 and Objective C

### ISSUE THREAD

**Issue by xthaohg** [marty-suzuki/SABlurImageView#36]
We need you support ios 10 and objective c
Thanks for support
excuse for translate google

**Comment by marty-suzuki** [comment]
Hi, @xthaohg !

I've added objective-c sample.
Please check this [sample file](https://github.com/marty-suzuki/SABlurImageView/blob/master/SABlurImageViewSample/SABlurImageViewSample/SampleViewController.m).

**Comment by xthaohg** [comment]
Thanks you!!!
